@startuml
START 
--> CHECKING_VERSIONS
--> BACKINGUP_DATABASE
--> COPYING_DATABASES
--> SCHEMA_UPDATE
--> SETUP_JPA
--> PRE_UPGRADE
--> ENTITY_UPGRADES
--> POST_UPGRADE
--> SHUTDOWN_JPA
--> DELETE_ORIG_DATABASE
--> COPY_NEW_DATABASE
--> DELETE_NEW_DATABASE
--> DELETE_OLD_DATABASE
--> COMPLETED
@enduml