@startuml
  title (Source,Dest) Migration State Tuples\nThe state machine from the CC PoV.
  state "Pending,none" as pendingnone
  state "Extant,none" as extantnone
  state "Teardown,none" as teardownnone
  state "Teardown,Extant" as teardownExtant
  state "none,Extant" as noneExtant
  state "none,Teardown" as noneTeardown
  state "Extant (preparing),none" as preparingnone
  state "Extant,Extant" as extantExtant {
    state "(preparing,preparing)" as preparingpreparing
    state "(ready,ready)" as readyready
    state "(preparing,ready)" as preparingready
'    state "(preparing,failed)" as preparingfailed
    state "(ready,preparing)" as readypreparing
'    state "(ready,failed)" as readyfailed
    state "(migrating,ready)" as migratingready
    state "(migrating,migrating)" as migratingmigrating
    state "(cleaning,migrating)" as cleaningmigrating
    state "(cleaning,none)" as cleaningnone
    state "(none,none)" as nonenone
    [*] -down-> preparingpreparing
    [*] -down-> readyready
    [*] -right-> preparingready
    [*] -left-> readypreparing
    preparingpreparing -up-> preparingready
    preparingpreparing -up-> readypreparing
    preparingready -down-> readyready
    readypreparing -down-> readyready
    readyready -down-> migratingready : ncMigrateInstances:COMMIT\non Source NC
    readyready -down-> migratingmigrating : ncMigrateInstances:COMMIT\non Source NC
    migratingready -right-> migratingmigrating
    migratingmigrating -down-> cleaningmigrating
    migratingmigrating -down-> nonenone
    migratingmigrating -down-> cleaningnone
    cleaningnone -right-> nonenone
    cleaningmigrating -right-> cleaningnone
    nonenone -down-> [*]
  }
  [*] -down-> pendingnone
  pendingnone -down-> extantnone
  pendingnone -left-> teardownnone
  extantnone -left-> teardownnone
  extantnone -down-> preparingnone : ncMigrateInstances:PREPARE\non Source NC
  preparingnone -down-> extantExtant : ncMigrateInstances:PREPARE\non Dest. NC
  extantExtant -down-> teardownExtant
  teardownExtant -down-> noneExtant
  noneExtant -down-> noneTeardown
  noneExtant -up-> extantnone : Another\ninstance\nmigration
  noneTeardown -down-> [*]
  teardownnone -down-> [*]
@enduml