@startuml
  title Source & Destination NC
  left to right direction 
  [*] -> Pending
  Pending -> Extant
  Pending -> Teardown
  Extant -> Teardown
  Extant -> Extant
  state Extant {
    state "preparing" as preparingSource 
    preparingSource : Source NC
    state "migrating" as migratingSource 
    migratingSource : Source NC
    state "ready" as readySource 
    readySource : Source NC
    state "Clean up" as cleanup
    cleanup : Source NC
    [*] -down-> preparingSource
    preparingSource -down-> readySource
    readySource -down-> migratingSource
    migratingSource -down-> cleanup
    cleanup -down-> [*] : Instance\ngoes to\nTeardown
    --
    state "preparing" as preparingDest
    preparingDest : Destination NC
    state "migrating" as migratingDest
    migratingDest : Destination NC
    state "ready" as readyDest
    readyDest : Destination NC
    [*] -down-> preparingDest
    preparingDest -down-> readyDest
    readyDest -down-> migratingDest
    migratingDest -down-> [*] : Instance\ngoes to\nExtant
  }
@enduml