@startuml image-service.png
!include ../../../lib/services.skin
skinparam ranksep 10
skinparam nodesep 10
scale 2000 width 
left to right direction
frame "EC2 Service" as EC2 {
  component "Import/Export Service" <<Service>> as impexservice
  interface ImportInstance
  interface ImportVolume
  interface DescribeConversionTasks
  interface CancelConversionTask
  interface CreateInstanceExportTask<<Future>>
  interface CancelExportTask<<Future>>
  interface DescribeExportTasks<<Future>>
  ImportInstance -- impexservice
  ImportVolume -- impexservice
  DescribeConversionTasks -- impexservice
  CancelConversionTask -- impexservice
  CreateInstanceExportTask -- impexservice
  CancelExportTask -- impexservice
  DescribeExportTasks -- impexservice
}
frame "Imaging Service" as imagingservice {
  interface ImportInstance as imgimportinst
  interface ImportVolume as imgimportvol 
  interface DescribeConversionTasks as imgdescribe
  interface CancelConversionTask as imgcancel
  interface ImportImage <<InternalOperation>> as imgimportimg
  interface ValidateImage <<ServiceInternalOperation>> as imgvalidateimg
  interface ConvertImage <<ServiceInternalOperation>> as imgconvertimg
  interface ValidateInstance <<ServiceInternalOperation>> as imgvalidateinst
  interface EncryptImage <<ServiceInternalOperation>> as imgcryptimg
  interface DecryptImage <<ServiceInternalOperation>> as imgdecryptimg
  interface BundleImage <<ServiceInternalOperation>> as imgbundleimg
  interface UnbundleImage <<ServiceInternalOperation>> as imgunbundleimg
  component "Imaging Workflow Engine" as imgworkflow
  imgimportinst -- imgworkflow
  imgimportvol -- imgworkflow
  imgdescribe -- imgworkflow
  imgimportimg -- imgworkflow
  imgvalidateimg -up- imgworkflow
  imgvalidateinst -up- imgworkflow
  imgconvertimg -up- imgworkflow
  imgcryptimg -up- imgworkflow
  imgdecryptimg -up- imgworkflow
  imgbundleimg  -up- imgworkflow
  imgunbundleimg -up- imgworkflow
  component "Image Toolkit" as imgtoolkit
  database "Local Work Cache" as imgcache
  imgworkflow -down- imgtoolkit
  imgtoolkit -down- imgcache
}
impexservice -- imgimportinst
impexservice -- imgimportvol
impexservice -- imgdescribe
impexservice -- imgcancel
frame Database {
  database "Conversion Task State" as taskstate
}
imgworkflow -left- taskstate
frame ObjectStorage {
    component "Input Bucket" as bucketin
    component "Output Bucket" as bucketout
}
frame NodeController {
  component BundleInstance
}
bucketin -up-> imgcache
imgcache -down-> bucketout
BundleInstance -up- imgimportimg
@enduml