@startuml
title RegisterImage (EC2 Service)

start
:#ffbbbb:RegisterImage invoked;
note right: Red indicates EC2 Service
if (imageLocation\nis valid) then (exists &\naccessible)
  :#ffbbbb:fetch\nmanifest;
  if (imageLocation's manifest\nis valid) then (yes)
    :#ffbbbb:populate\nmetadata\nfrom manifest;
    fork
      :#ddffdd:<b>Call:</b>\nRegisterImage;
      note right: green indicates\nImaging Service
      fork
        while (imaging task not complete)
          :#ffbbbb:check imaging task;
          :#ddffdd:<b>Call:</b>\nDescribeImagingTasks;
        endwhile
        :#ffbbbb:image state\navailable;
      fork again
        :#ddffdd:<b>Executes</b>\nRegisterImage workflow;
      endfork
    fork again
      :#ffbbbb:image state\nunavailable;
      :#ffbbbb:assign\nimage id;
      :#ffbbbb:<b>return image id</b>;
      end
    endfork
  else (invalid)
    :#ffbbbb:<b>return error</b>;
    end
  endif
else (invalid)
  :#ffbbbb:<b>return error</b>;
  end
endif
end
@enduml