@startuml

title Disable Alarm Actions Workflow

rectangle {
    ()"Cloud Watch Service"
}
() "Cloud Watch Service" --> (DisableAlarmActions): response
(DisableAlarmActions) -down-> ()"Cloud Watch Service" : request
() "Cloud Watch Service" --> (Alarms) : UPDATE
database "eucalyptus_cloudwatch" {
folder "Alarms" {
  }
}
@enduml


