@startuml

title List Metrics Workflow

rectangle {
    ()"Cloud Watch Service"
}
() "Cloud Watch Service" --> (ListMetrics): response
(ListMetrics) -down-> ()"Cloud Watch Service" : request
(PutMetricData) --> [Raw Data Queue]
[Raw Data Queue] --> (Aggregation)
[Raw Data Queue] <-right- (Aggregation)
database "eucalyptus_cloudwatch" {
folder "List Metric Rows" {
    [list_metrics]
  }
}
[list_metrics] o-- (Aggregation) : INSERT/UPDATE
(Cleaner) --left-> [list_metrics] : DELETE
() "Cloud Watch Service" -down-> [list_metrics]: READ
@enduml
