@startuml

title Put Metric Data Workflow

rectangle {
    ()"Cloud Watch Service"
}
() "Cloud Watch Service" --> (PutMetricData): response
(PutMetricData) -down-> ()"Cloud Watch Service" : request
() "Cloud Watch Service" -down-> [Raw Data Queue]
[Raw Data Queue] --> (Aggregation)
[Raw Data Queue] <-right- (Aggregation)
database "eucalyptus_cloudwatch" {
folder "Data Points Rows" {
    [Metric Data table (based on hash and metric type)]
  }
}
[Metric Data table (based on hash and metric type)] <-- (Aggregation) : INSERT
(Cleaner) --left-> [Metric Data table (based on hash and metric type)] : DELETE
@enduml
