@startuml

title Set Alarm State Workflow

rectangle {
    ()"Cloud Watch Service"
}
() "Cloud Watch Service" --> (SetAlarmState): response
(SetAlarmState) -down-> ()"Cloud Watch Service" : request
() "Cloud Watch Service" --> (Alarms) : UPDATE
database "eucalyptus_cloudwatch" {
folder "Alarms" {
  }
}
@enduml


